source 'https://rubygems.org'

gem 'rails', '4.2.7.1'
gem 'mysql2', '>= 0.3.13', '< 0.5'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'

gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'unicorn'

gem 'devise', '~> 3.5'
gem 'foundation-rails', '5.5.2.1'
gem 'paperclip', '~> 4.3'
gem 'aws-sdk', '~> 1.65'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

